### ISSUE TITLE
Tests fail on Windows 10

### ISSUE THREAD

**Issue by Odud** [cosimo/perl6-string-crc32#8]
Tests fail and so won't install on Windows 10 (This is perl6 version 2015.09 built on MoarVM version 2015.09)

PS C:\Users\langb\dropbox\perl6\images> panda install String::CRC32
==> Fetching String::CRC32
==> Building String::CRC32
==> Testing String::CRC32
t/000-load-module.t .. ok

\# Failed test 'Test the CRC of a file handle'
\# at t/crc.t line 33
\# expected: '1925609391'
\#      got: '443916274'
\# Looks like you failed 1 test of 6
t/crc.t ..............
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests

**Comment by cosimo** [comment]
I wonder if this is because of line endings being interpreted differently on Windows.

**Comment by Odud** [comment]
Cosimo, I think you could be right, I'm running on the 2015.09 release and think I am seeing some inconsistencies in how EOL is handled in other areas. I will retest once the official release is available.

Pete Barlow

-----Original Message-----

**Comment by cosimo** [comment]
Current master should fix this. Can you confirm?

**Comment by Odud** [comment]
Hi Cosimo,

It is still failing for me but I suspect it is because I am currently
running 2015.09. I will wait until I have the latest Rakudo Star (.msi)
installed and then retest, hopefully it will be available in the next few
days.

Pete

*Pete Barlow*

**Comment by Odud** [comment]
Now that I'm running 2015.01.1 the module passes the tests and installs fine
